### ISSUE TITLE
Cannot run demo

### ISSUE THREAD

**Issue by xtenduke** [edgio-docs/edgio-nextjs-example#3]
PopOs 21.04
npm 7.22.0
node v14.17.0

Cloned repo, installed with npm
started with `layer0 dev`

Install and run log below

```jake@vulcan:~/Development/layer0-nextjs-example$ npm install
npm WARN deprecated @types/chalk@2.2.0: This is a stub types definition for chalk (https://github.com/chalk/chalk). chalk provides its own type definitions, so you don't need @types/chalk installed!
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/pinpoint@1.0.2: Moved to 'npm install @sideway/pinpoint'
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated @hapi/vise@3.1.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/subtext@6.1.3: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/teamwork@3.3.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/statehood@6.1.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/nigel@3.1.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/podium@3.4.3: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/mimos@4.1.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/heavy@6.2.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/file@1.0.0: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/cryptiles@4.2.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/content@4.1.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/catbox-memory@4.1.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/ammo@3.1.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/pez@4.1.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/iron@5.1.4: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/b64@4.2.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated @hapi/somever@2.1.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/shot@4.1.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/call@5.1.3: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/accept@3.2.4: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated @hapi/formula@1.2.0: Moved to 'npm install @sideway/formula'
npm WARN deprecated @hapi/bounce@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/catbox@10.2.3: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/wreck@15.1.0: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hapi@18.4.1: This version contains severe security issues and defects and should not be used! Please upgrade to the latest version of @hapi/hapi or consider a commercial license (https://github.com/hapijs/hapi/issues/4114)
npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm WARN deprecated @hapi/joi@16.1.8: Switch to 'npm install joi'
npm WARN deprecated @hapi/joi@16.1.8: Switch to 'npm install joi'
npm WARN deprecated @hapi/joi@16.1.8: Switch to 'npm install joi'
npm WARN deprecated @hapi/joi@16.1.8: Switch to 'npm install joi'
npm WARN deprecated @hapi/joi@16.1.8: Switch to 'npm install joi'
npm WARN deprecated @hapi/joi@16.1.8: Switch to 'npm install joi'
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

added 1848 packages, and audited 1849 packages in 21s

100 packages are looking for funding
  run `npm fund` for details

31 vulnerabilities (21 moderate, 8 high, 2 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
jake@vulcan:~/Development/layer0-nextjs-example$ layer0 dev
> Starting Layer0 in development mode with caching disabled...
Next (node:22507) [DEP_WEBPACK_SINGLE_ENTRY_PLUGIN] DeprecationWarning: SingleEntryPlugin was renamed to EntryPlugin
(Use `node --trace-deprecation ...` to show where the warning was created)
Next warn  - Minimum recommended TypeScript version is v4.3.2, older versions can potentially be incompatible with Next.js. Detected: 4.2.3
Next Defining routes from exportPathMap
> getting rewrites and redirects from next config
(node:22464) [DEP_WEBPACK_SINGLE_ENTRY_PLUGIN] DeprecationWarning: SingleEntryPlugin was renamed to EntryPlugin
(Use `node --trace-deprecation ...` to show where the warning was created)
webpack compiled successfully
error TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
    at Object.watch (fs.js:1578:11)
    at new NextRoutes (/home/jake/Development/layer0-nextjs-example/.layer0/lambda/routes.js:7003:18)
    at Object../node_modules/@layer0/next/router/index.js (/home/jake/Development/layer0-nextjs-example/.layer0/lambda/routes.js:7453:22)
    at __webpack_require__ (/home/jake/Development/layer0-nextjs-example/.layer0/lambda/routes.js:18588:42)
    at Object../node_modules/@layer0/next/index.js (/home/jake/Development/layer0-nextjs-example/.layer0/lambda/routes.js:6933:10)
    at __webpack_require__ (/home/jake/Development/layer0-nextjs-example/.layer0/lambda/routes.js:18588:42)
    at Object../routes.ts (/home/jake/Development/layer0-nextjs-example/.layer0/lambda/routes.js:17367:14)
    at __webpack_require__ (/home/jake/Development/layer0-nextjs-example/.layer0/lambda/routes.js:18588:42)
    at /home/jake/Development/layer0-nextjs-example/.layer0/lambda/routes.js:18652:37
    at /home/jake/Development/layer0-nextjs-example/.layer0/lambda/routes.js:18655:12
    at webpackUniversalModuleDefinition (/home/jake/Development/layer0-nextjs-example/.layer0/lambda/routes.js:3:20)
    at Object.<anonymous> (/home/jake/Development/layer0-nextjs-example/.layer0/lambda/routes.js:10:3)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14) {
  code: 'ERR_FEATURE_UNAVAILABLE_ON_PLATFORM'
}
(node:22464) UnhandledPromiseRejectionWarning: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
    at Object.watch (fs.js:1578:11)
    at new NextRoutes (/home/jake/Development/layer0-nextjs-example/.layer0/lambda/routes.js:7003:18)
    at Object../node_modules/@layer0/next/router/index.js (/home/jake/Development/layer0-nextjs-example/.layer0/lambda/routes.js:7453:22)
    at __webpack_require__ (/home/jake/Development/layer0-nextjs-example/.layer0/lambda/routes.js:18588:42)
    at Object../node_modules/@layer0/next/index.js (/home/jake/Development/layer0-nextjs-example/.layer0/lambda/routes.js:6933:10)
    at __webpack_require__ (/home/jake/Development/layer0-nextjs-example/.layer0/lambda/routes.js:18588:42)
    at Object../routes.ts (/home/jake/Development/layer0-nextjs-example/.layer0/lambda/routes.js:17367:14)
    at __webpack_require__ (/home/jake/Development/layer0-nextjs-example/.layer0/lambda/routes.js:18588:42)
    at /home/jake/Development/layer0-nextjs-example/.layer0/lambda/routes.js:18652:37
    at /home/jake/Development/layer0-nextjs-example/.layer0/lambda/routes.js:18655:12
    at webpackUniversalModuleDefinition (/home/jake/Development/layer0-nextjs-example/.layer0/lambda/routes.js:3:20)
    at Object.<anonymous> (/home/jake/Development/layer0-nextjs-example/.layer0/lambda/routes.js:10:3)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
(node:22464) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22464) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Next > Creating service worker...
Next (node:22507) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
	Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
	Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
Next > Creating service worker...
Next warn  - InjectManifest has been called multiple times, perhaps due to running webpack in --watch mode. The precache manifest generated after the first call may be inaccurate! Please see https://github.com/GoogleChrome/workbox/issues/1790 for more information.

static/chunks/pages/_app.js is 8.68 MB, and won't be precached. Configure maximumFileSizeToCacheInBytes to change this limit.

static/chunks/main.js is 4.41 MB, and won't be precached. Configure maximumFileSizeToCacheInBytes to change this limit.
Next info  - ready on http://localhost:3001
Next wait  - compiling...
Next warn  - InjectManifest has been called multiple times, perhaps due to running webpack in --watch mode. The precache manifest generated after the first call may be inaccurate! Please see https://github.com/GoogleChrome/workbox/issues/1790 for more information.

static/chunks/pages/_app.js is 8.68 MB, and won't be precached. Configure maximumFileSizeToCacheInBytes to change this limit.

static/chunks/main.js is 4.41 MB, and won't be precached. Configure maximumFileSizeToCacheInBytes to change this limit.
Next info  - ready on http://localhost:3001
(node:22464) UnhandledPromiseRejectionWarning: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
    at Object.watch (fs.js:1578:11)
    at new NextRoutes (/home/jake/Development/layer0-nextjs-example/.layer0/lambda/routes.js:7003:18)
    at Object../node_modules/@layer0/next/router/index.js (/home/jake/Development/layer0-nextjs-example/.layer0/lambda/routes.js:7453:22)
    at __webpack_require__ (/home/jake/Development/layer0-nextjs-example/.layer0/lambda/routes.js:18588:42)
    at Object../node_modules/@layer0/next/index.js (/home/jake/Development/layer0-nextjs-example/.layer0/lambda/routes.js:6933:10)
    at __webpack_require__ (/home/jake/Development/layer0-nextjs-example/.layer0/lambda/routes.js:18588:42)
    at Object../routes.ts (/home/jake/Development/layer0-nextjs-example/.layer0/lambda/routes.js:17367:14)
    at __webpack_require__ (/home/jake/Development/layer0-nextjs-example/.layer0/lambda/routes.js:18588:42)
    at /home/jake/Development/layer0-nextjs-example/.layer0/lambda/routes.js:18652:37
    at /home/jake/Development/layer0-nextjs-example/.layer0/lambda/routes.js:18655:12
    at webpackUniversalModuleDefinition (/home/jake/Development/layer0-nextjs-example/.layer0/lambda/routes.js:3:20)
    at Object.<anonymous> (/home/jake/Development/layer0-nextjs-example/.layer0/lambda/routes.js:10:3)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
(node:22464) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)```

**Comment by rishi-raj-jain** [comment]
Just did a clone and ran npm install. This is what I see, followed by a successful run of the app with `layer0 dev`. Also, to update layer0 dependencies, run `layer0 use latest` in your project root directory with bash/cmd. Hope this resolves your issue @xtenduke


> fsevents@1.2.13 install /Users/rishi-raj-jain/Desktop/layer0-nextjs-example/node_modules/watchpack-chokidar2/node_modules/fsevents
> node install.js

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> core-js@2.6.12 postinstall /Users/rishi-raj-jain/Desktop/layer0-nextjs-example/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> ejs@2.7.4 postinstall /Users/rishi-raj-jain/Desktop/layer0-nextjs-example/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> esbuild@0.11.23 postinstall /Users/rishi-raj-jain/Desktop/layer0-nextjs-example/node_modules/esbuild
> node install.js


> protobufjs@6.10.2 postinstall /Users/rishi-raj-jain/Desktop/layer0-nextjs-example/node_modules/protobufjs
> node scripts/postinstall


> serverless@1.83.3 postinstall /Users/rishi-raj-jain/Desktop/layer0-nextjs-example/node_modules/serverless
> node ./scripts/postinstall.js


   ┌───────────────────────────────────────────────────┐
   │                                                   │
   │   Serverless Framework successfully installed!    │
   │                                                   │
   │   To start your first project run 'serverless'.   │
   │                                                   │
   └───────────────────────────────────────────────────┘

added 1926 packages from 883 contributors and audited 1928 packages in 23.077s

100 packages are looking for funding
  run `npm fund` for details

found 41 vulnerabilities (32 moderate, 8 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by rishi-raj-jain** [comment]
@xtenduke Does this solve your issue?

**Comment by xtenduke** [comment]
@rishi-raj-jain yes `layer0 use latest` resolves it. Cheers
